### ISSUE TITLE
How to integrate Waterbus data in the findParking results?

### ISSUE THREAD

**Issue by didiercarels** [AaltoAsia/O-MI#18]
What is the best way to proceed in order to allow the BMW i3 screen to display the integrated information between the Parking slot and the Waterbus stop?
Do we have to add a method in the Waterbus OMI node to find the nearest parking slot? Or, do we have to add a method in the Parking OMI node to find the nearest Waterbus stop?

**Comment by TK009** [comment]
You need to start the `ParkingAgent` that is supplied with O-MI Node and write mobivoc typed ParkingFacilities for it. 

Here is more detailed steps to follow:

1. Find the `ParkingAgent` in the application.conf and uncomment all related settings.
2. Restart O-MI Node and check `logs/omi.log` that the configuration syntax was correct and ParkingAgent was loaded on startup.
3. Create your `ParkingFacility` objects. You can see an example use of some mobivoc and schema.org types [under line 185 here](https://github.com/AaltoAsia/O-MI/blob/master/conf/ParkingServiceOdf.xml#L185). I think that the InfoItems for BMW screen are:
    * `ParkingFacility`
        - `geo`
        - `name`
        - `operatedBy`
        - `url`
        - `Capacities` (this structure is optional)
            * `CarCapacity`
               - `maximumValue`
               - `realTimeValue`
4. Don't forget the prefix attribute,  [line 2 of the example](https://github.com/AaltoAsia/O-MI/blob/master/conf/ParkingServiceOdf.xml#L2)
5. Write your ParkingFacilities under `/Objects/ParkingService/ParkingFacilities/` as in the example for best chance of working correctly in all systems.
6. Make sure you have registered your O-MI Node in IoTBnB.
