### ISSUE TITLE
Mapping from O-DF hierarchy to Warp 10 could retain the '/' as separator

### ISSUE THREAD

**Issue by hbs** [AaltoAsia/O-MI#6]
Warp 10 does not impose any restriction on class names, so they can perfectly contain slashes, there is no need to convert them to dots, thus retaining the original hierarchy making things easier.

**Comment by TK009** [comment]
Okay, we somehow assumed it would conflict with the input syntax without properly testing it. We can take a look on this in the next sprint.

**Comment by TK009** [comment]
Fixed in 356cf4348809d59641e5a4069da0b0b35fda236a.
