### ISSUE TITLE
find parking results

### ISSUE THREAD

**Issue by fl-ma** [AaltoAsia/O-MI#9]
when issuing a findParking request for user group mv:Families, the returned parking information seems to be inconsistent.

the <capacities> object for "Otaniemi Campus Library" is completely empty. 
however the parking spaces themselves are returned.

either the usergroup should strictly limit to exclusively that value (not recommended from my side) or the normal capacities (not limited to a certain usergroup) should also be shown when filtering for a certain usergroup.

tested with http://biotope.cs.hut.fi; 

[20180802 findParking families response.txt](https://github.com/AaltoAsia/O-MI/files/2252616/20180802.findParking.families.response.txt)
[20180802 findParking families.txt](https://github.com/AaltoAsia/O-MI/files/2252617/20180802.findParking.families.txt)

see attachments for details

**Comment by TK009** [comment]
fd53ba8 might fix the problem

**Comment by TK009** [comment]
We resolved this issue by including the normal capacities like you suggested.
